# Generated by Django 3.1.2 on 2020-12-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('content1', models.CharField(max_length=5000)),
                ('sub_heading1', models.CharField(max_length=100)),
                ('sub_heading2', models.CharField(default='', max_length=100)),
                ('content2', models.CharField(default='', max_length=5000)),
                ('content3', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(upload_to='blog/images')),
            ],
        ),
    ]
