# Generated by Django 3.1.2 on 2020-12-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201217_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
