# Generated by Django 3.1.2 on 2020-12-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20201220_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='amount',
            new_name='amnt',
        ),
    ]
